name: Build
on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
      - synchronize
  push:

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2

    - name: package install
      run: ./ci_prereq.sh

    - name: build
      id: build
      run: ./build.sh
    - name: log
      if: ${{ always() && (steps.build.outcome == 'failure') }}
      run: |
        echo "output.log"
        cat ~/.dosemu/boot.log
